// Generated by PromptJS Compiler v0.9
// Source: promptjs

// === Runtime Helpers ===
var __subscribers = new WeakMap();
var __effectMap = new WeakMap();
var __activeEffect = null;
var __effectId = 0;

function __createReactive(val) {
  var obj = { value: val, __id: ++__effectId };
  var proxy = new Proxy(obj, {
    get: function (target, prop) {
      if (__activeEffect && prop === 'value') {
        var subs = __subscribers.get(proxy) || new Set();
        subs.add(__activeEffect);
        __subscribers.set(proxy, subs);
        if (__activeEffect.__deps) __activeEffect.__deps.add(proxy);
      }
      return target[prop];
    },
    set: function (target, prop, newVal) {
      var oldVal = target[prop];
      target[prop] = newVal;
      if (prop === 'value' && oldVal !== newVal) {
        var subs = __subscribers.get(proxy);
        if (subs) {
          var subsCopy = Array.from(subs);
          for (var i = 0; i < subsCopy.length; i++) subsCopy[i](newVal, oldVal);
        }
      }
      return true;
    },
  });
  return proxy;
}

function __watch(reactive, cb) {
  var effect = function watchEffect(n, o) {
    cb(n, o);
  };
  effect.__deps = new Set();
  var subs = __subscribers.get(reactive) || new Set();
  subs.add(effect);
  __subscribers.set(reactive, subs);
  try {
    cb(reactive.value, undefined);
  } catch (e) {
    /* defer if deps not ready */
  }
  var unsub = function unsubscribe() {
    var s = __subscribers.get(reactive);
    if (s) s.delete(effect);
  };
  return unsub;
}

function __setState(reactive, val) {
  reactive.value = val;
}

function __pjs_handleError(error, context, hook) {
  console.error('[PromptJS] Error di ' + context + '.' + hook + ':', error);
  if (window.__pjsClearError) {
    window.__pjsClearError();
  }
}

// === User Code ===
(function () {
  // @source 0:0 TetapDeclaration
  const judul = 'Todo App';
  // @source 0:0 TetapDeclaration
  const todos =
    '[{"teks":"Belajar PromptJS","selesai":benar},{"teks":"Buat aplikasi pertama","selesai":salah},{"teks":"Deploy ke internet","selesai":salah}]';
  // @source 6:1 BuatStatement
  const __el_1 = document.createElement('div');
  __el_1.id = 'todoapp';
  const daftar = __createReactive([]);
  const tugas = __createReactive('');
  __el_1.addEventListener('load', (event) => {
    try {
      __setState(daftar, todos);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_muat');
    }
  });
  const __el_3 = document.createElement('h1');
  __el_3.innerText = judul;
  __el_1.appendChild(__el_3);
  const __el_4 = document.createElement('div');
  __el_4.className = 'input-bar';
  const __el_6 = document.createElement('input');
  __el_6.placeholder = 'Tulis tugas baru...';
  __el_6.addEventListener('input', (event) => {
    try {
      __setState(tugas, document.querySelector('input').value);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_diketik');
    }
  });
  __el_4.appendChild(__el_6);
  const __el_8 = document.createElement('button');
  const __txt_10 = document.createTextNode('Tambah');
  __el_8.appendChild(__txt_10);
  __el_8.addEventListener('click', (event) => {
    try {
      daftar.value.push(tugas.value);
      __setState(daftar, [...daftar.value]);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_diklik');
    }
  });
  __el_4.appendChild(__el_8);
  __el_1.appendChild(__el_4);
  const __el_11 = document.createElement('ul');
  __el_11.className = 'todo-list';
  daftar.value.forEach((item, indeks) => {
    const __el_12 = document.createElement('li');
    __el_12.className = 'todo-item';
    const __el_14 = document.createElement('span');
    __el_14.className = 'todo-teks';
    const __txt_15 = document.createTextNode(String(item));
    __el_14.appendChild(__txt_15);
    __el_12.appendChild(__el_14);
    const __el_16 = document.createElement('button');
    __el_16.className = 'hapus-btn';
    const __txt_18 = document.createTextNode('✕');
    __el_16.appendChild(__txt_18);
    __el_16.addEventListener('click', (event) => {
      try {
        ((daftar.value = daftar.value.filter((__item) => __item !== item)),
          __setState(daftar, [...daftar.value]));
      } catch (__e) {
        __pjs_handleError(__e, 'fragment', 'on_diklik');
      }
    });
    __el_12.appendChild(__el_16);
    __el_11.appendChild(__el_12);
  });
  __el_1.appendChild(__el_11);
  const __wmarker_19 = document.createElement('span');
  __wmarker_19.className = '__promptjs_watcher_marker';
  __el_1.appendChild(__wmarker_19);
  __watch(daftar, (nilaiBaru, nilaiLama) => {
    __wmarker_19.innerHTML = '';
    const __el_20 = document.createElement('div');
    __el_20.className = 'status';
    const __el_22 = document.createElement('span');
    const __txt_23 = document.createTextNode(String(daftar.value.length));
    __el_22.appendChild(__txt_23);
    __el_20.appendChild(__el_22);
    const __el_24 = document.createElement('span');
    const __txt_25 = document.createTextNode(' tugas');
    __el_24.appendChild(__txt_25);
    __el_20.appendChild(__el_24);
    __wmarker_19.appendChild(__el_20);
  });
  document.body.appendChild(__el_1);
})();
