// Generated by PromptJS Compiler v0.9
// Source: promptjs
// Mode: SPA (router active)
// Auth: Protected by authentication guard

// === User Code ===
// Auth guard: check localStorage for token
(function() {
  var __token = localStorage.getItem('auth_token');
  if (!__token) {
    window.location.href = '/login';
    return;
  }

  var __cleanupFns = [];
  var __dipasangFns = [];
  var __dilepasFns = [];
  
    // @source 0:0 TetapDeclaration
    const tokenKey = "auth_token";
    // @source 8:1 BuatStatement
    const __el_1 = document.createElement("div");
    __el_1.id = "dashboardapp";
    const __el_3 = document.createElement("nav");
    __el_3.id = "navigasi";
    const __el_5 = document.createElement("span");
    __el_5.className = "logo";
    const __txt_6 = document.createTextNode("Dashboard");
    __el_5.appendChild(__txt_6);
    __el_3.appendChild(__el_5);
    const __el_7 = document.createElement("tombol[data-halaman="dashboard"]");
    const __txt_8 = document.createTextNode("Dashboard");
    __el_7.appendChild(__txt_8);
    __el_3.appendChild(__el_7);
    const __el_9 = document.createElement("tombol[data-halaman="profil"]");
    const __txt_10 = document.createTextNode("Profil");
    __el_9.appendChild(__txt_10);
    __el_3.appendChild(__el_9);
    const __el_11 = document.createElement("tombol[data-halaman="pengaturan"]");
    const __txt_12 = document.createTextNode("Pengaturan");
    __el_11.appendChild(__txt_12);
    __el_3.appendChild(__el_11);
    const __el_13 = document.createElement("button");
    __el_13.id = "keluar";
    __el_13.className = "keluar";
    const __txt_14 = document.createTextNode("Keluar");
    __el_13.appendChild(__txt_14);
    __el_3.appendChild(__el_13);
    __el_1.appendChild(__el_3);
    const __el_15 = document.createElement("div");
    __el_15.id = "konten";
    const __el_16 = document.createElement("h2");
    const __txt_17 = document.createTextNode("Memuat...");
    __el_16.appendChild(__txt_17);
    __el_15.appendChild(__el_16);
    __el_1.appendChild(__el_15);
  
  return {
    el: __el_1,
    mount: function(__parent) {
      (__parent || document.body).appendChild(__el_1);
      __dipasangFns.forEach(function(fn) { fn(); });
    },
    unmount: function() {
      __dilepasFns.forEach(function(fn) { fn(); });
      __cleanupFns.forEach(function(fn) { fn(); });
      if (__el_1) __el_1.remove();
    }
  };
})();