#!/bin/bash
# =============================================================
# Panduan Push PromptJS ke GitHub via Termux
# Repo: github.com/raarion/promptjs
# =============================================================
#
# Karena file sudah disalin ke:
#   /storage/emulated/0/Documents/promptjs/
#
# Lakukan langkah-langkah berikut di Termux:
#

echo "============================================"
echo " LANGKAH 1: Install git di Termux (jika belum)"
echo "============================================"
echo "  pkg install git"
echo ""

echo "============================================"
echo " LANGKAH 2: Konfigurasi git"
echo "============================================"
echo "  git config --global user.name  'raarion'"
echo "  git config --global user.email 'email@kamu.com'"
echo "  # Ganti email@kamu.com dengan email GitHub-mu!"
echo ""

echo "============================================"
echo " LANGKAH 3: Buat repo di GitHub"
echo "============================================"
echo "  Cara A (browser — lebih mudah):"
echo "    1. Buka https://github.com/new"
echo "    2. Login sebagai raarion"
echo "    3. Repository name: promptjs"
echo "    4. Description: A mini-DSL template engine that compiles to vanilla JS"
echo "    5. Public ✓"
echo "    6. JANGAN centang README, .gitignore, atau license"
echo "       (karena kita sudah punya sendiri)"
echo "    7. Klik 'Create repository'"
echo ""
echo "  Cara B (gh CLI — jika terinstal):"
echo "    pkg install gh"
echo "    gh auth login"
echo "    gh repo create promptjs --public --description 'A mini-DSL template engine that compiles to vanilla JS'"
echo ""

echo "============================================"
echo " LANGKAH 4: Pindah ke folder project"
echo "============================================"
echo "  cd /storage/emulated/0/Documents/promptjs/"
echo ""

echo "============================================"
echo " LANGKAH 5: Inisialisasi git"
echo "============================================"
echo "  git init"
echo ""

echo "============================================"
echo " LANGKAH 6: Tambahkan remote"
echo "============================================"
echo "  git remote add origin https://github.com/raarion/promptjs.git"
echo ""

echo "============================================"
echo " LANGKAH 7: Tambahkan file PromptJS saja"
echo "============================================"
echo "  Pastikan .gitignore sudah ada di folder, lalu:"
echo "  git add .gitignore"
echo "  git add README.md"
echo "  git add package.json"
echo "  git add PromptJS-Spec-v0.1.md"
echo "  git add PromptJS-Spec-v0.2.md"
echo "  git add PromptJS-Evaluasi-Arsitektur.md"
echo "  git add src/"
echo ""

echo "============================================"
echo " LANGKAH 8: Cek apa yang akan di-commit"
echo "============================================"
echo "  git status"
echo "  # Pastikan TIDAK ada file dari:"
echo "  #   - direktori clone lama"
echo "  #   - browser-data/ atau .browser_data/"
echo "  #   - .agent_hooks/ atau .agent-hooks/"
echo "  #   - summarized_conversations/"
echo "  #   - outputs/"
echo "  #   - .psiphon_data/"
echo "  #   - todo.md"
echo "  # Jika ada yang lolos, periksa .gitignore"
echo ""

echo "============================================"
echo " LANGKAH 9: Commit pertama"
echo "============================================"
echo "  git commit -m 'feat: initial commit — PromptJS v0.1.0"
echo "  "
echo "  - 5-stage pipeline: Lexer → Parser → Resolver → Analyzer → Compiler"
echo "  - Bilingual keywords (Indonesia/English)"
echo "  - Front-matter data binding"
echo "  - Event & tag alias maps"
echo "  - CLI: compile, serve, build, init"
echo "  - 24 tests passing'"
echo ""

echo "============================================"
echo " LANGKAH 10: Push ke GitHub"
echo "============================================"
echo "  git branch -M main"
echo "  git push -u origin main"
echo ""

echo "============================================"
echo " SELESAI!"
echo "============================================"
echo "  Cek repo: https://github.com/raarion/promptjs"
echo ""
