// Generated by PromptJS Compiler v0.9
// Source: promptjs

// === Runtime Helpers ===
var __subscribers = new WeakMap();
var __effectMap = new WeakMap();
var __activeEffect = null;
var __effectId = 0;

function __createReactive(val) {
  var obj = { value: val, __id: ++__effectId };
  var proxy = new Proxy(obj, {
    get: function (target, prop) {
      if (__activeEffect && prop === 'value') {
        var subs = __subscribers.get(proxy) || new Set();
        subs.add(__activeEffect);
        __subscribers.set(proxy, subs);
        if (__activeEffect.__deps) __activeEffect.__deps.add(proxy);
      }
      return target[prop];
    },
    set: function (target, prop, newVal) {
      var oldVal = target[prop];
      target[prop] = newVal;
      if (prop === 'value' && oldVal !== newVal) {
        var subs = __subscribers.get(proxy);
        if (subs) {
          var subsCopy = Array.from(subs);
          for (var i = 0; i < subsCopy.length; i++) subsCopy[i](newVal, oldVal);
        }
      }
      return true;
    },
  });
  return proxy;
}

function __setState(reactive, val) {
  reactive.value = val;
}

function __pjs_handleError(error, context, hook) {
  console.error('[PromptJS] Error di ' + context + '.' + hook + ':', error);
  if (window.__pjsClearError) {
    window.__pjsClearError();
  }
}

// === User Code ===
(function () {
  // @source 0:0 TetapDeclaration
  const judul = 'Dashboard';
  // @source 6:1 BuatStatement
  const __el_1 = document.createElement('div');
  __el_1.id = 'dashboard';
  const hitung = __createReactive(0);
  const pengunjung = __createReactive(42);
  __el_1.addEventListener('load', (event) => {
    try {
      __setState(pengunjung, 42);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_muat');
    }
  });
  const __el_3 = document.createElement('h2');
  const __txt_4 = document.createTextNode('Dashboard Admin');
  __el_3.appendChild(__txt_4);
  __el_1.appendChild(__el_3);
  const __el_5 = document.createElement('div');
  __el_5.className = 'stats';
  const __el_7 = document.createElement('div');
  __el_7.className = 'kartu-stat';
  const __el_9 = document.createElement('span');
  __el_9.className = 'angka';
  __el_9.innerText = hitung.value;
  __el_7.appendChild(__el_9);
  const __el_10 = document.createElement('span');
  __el_10.className = 'label';
  const __txt_11 = document.createTextNode('Counter');
  __el_10.appendChild(__txt_11);
  __el_7.appendChild(__el_10);
  const __el_12 = document.createElement('button');
  __el_12.id = 'tambah';
  __el_12.className = 'besar';
  const __txt_13 = document.createTextNode('+');
  __el_12.appendChild(__txt_13);
  __el_7.appendChild(__el_12);
  __el_7.addEventListener('click', (event) => {
    try {
      __setState(hitung, hitung + 1);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_diklik');
    }
  });
  __el_5.appendChild(__el_7);
  const __el_14 = document.createElement('button');
  __el_14.id = 'kurang';
  __el_14.className = 'besar';
  const __txt_15 = document.createTextNode('−');
  __el_14.appendChild(__txt_15);
  __el_5.appendChild(__el_14);
  __el_5.addEventListener('click', (event) => {
    try {
      __setState(document, document.querySelector('1') - 1);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_diklik');
    }
  });
  const __txt_16 = document.createTextNode(String(hitung.value));
  __el_5.appendChild(__txt_16);
  __el_1.appendChild(__el_5);
  document.body.appendChild(__el_1);
  // @source 23:9 BuatStatement
  const __el_17 = document.createElement('div');
  __el_17.className = 'kartu-stat';
  const __el_19 = document.createElement('span');
  __el_19.className = 'angka';
  __el_19.innerText = pengunjung;
  __el_17.appendChild(__el_19);
  const __el_20 = document.createElement('span');
  __el_20.className = 'label';
  const __txt_21 = document.createTextNode('Pengunjung');
  __el_20.appendChild(__txt_21);
  __el_17.appendChild(__el_20);
  document.body.appendChild(__el_17);
})();
