// Generated by PromptJS Compiler v0.9
// Source: promptjs

// === Runtime Helpers ===
var __subscribers = new WeakMap();
var __effectMap = new WeakMap();
var __activeEffect = null;
var __effectId = 0;

function __createReactive(val) {
  var obj = { value: val, __id: ++__effectId };
  var proxy = new Proxy(obj, {
    get: function (target, prop) {
      if (__activeEffect && prop === 'value') {
        var subs = __subscribers.get(proxy) || new Set();
        subs.add(__activeEffect);
        __subscribers.set(proxy, subs);
        if (__activeEffect.__deps) __activeEffect.__deps.add(proxy);
      }
      return target[prop];
    },
    set: function (target, prop, newVal) {
      var oldVal = target[prop];
      target[prop] = newVal;
      if (prop === 'value' && oldVal !== newVal) {
        var subs = __subscribers.get(proxy);
        if (subs) {
          var subsCopy = Array.from(subs);
          for (var i = 0; i < subsCopy.length; i++) subsCopy[i](newVal, oldVal);
        }
      }
      return true;
    },
  });
  return proxy;
}

function __setState(reactive, val) {
  reactive.value = val;
}

function __pjs_handleError(error, context, hook) {
  console.error('[PromptJS] Error di ' + context + '.' + hook + ':', error);
  if (window.__pjsClearError) {
    window.__pjsClearError();
  }
}

// === User Code ===
(function () {
  // @source 0:0 TetapDeclaration
  const judul = 'Masuk';
  // @source 5:1 BuatStatement
  const __el_1 = document.createElement('div');
  __el_1.id = 'login';
  const nama = __createReactive('');
  const sandi = __createReactive('');
  const pesan = __createReactive('');
  const __el_3 = document.createElement('div');
  __el_3.className = 'kartu-login';
  const __el_5 = document.createElement('h2');
  const __txt_6 = document.createTextNode('Masuk ke Dashboard');
  __el_5.appendChild(__txt_6);
  __el_3.appendChild(__el_5);
  const __el_7 = document.createElement('formulir');
  const __el_9 = document.createElement('label');
  const __txt_10 = document.createTextNode('Nama Pengguna');
  __el_9.appendChild(__txt_10);
  __el_7.appendChild(__el_9);
  const __el_11 = document.createElement('input');
  __el_11.id = 'nama';
  __el_11.placeholder = 'admin';
  __el_11.addEventListener('input', (event) => {
    try {
      __setState(nama, document.querySelector('#nama').value);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_diketik');
    }
  });
  __el_7.appendChild(__el_11);
  const __el_13 = document.createElement('label');
  const __txt_14 = document.createTextNode('Kata Sandi');
  __el_13.appendChild(__txt_14);
  __el_7.appendChild(__el_13);
  const __el_15 = document.createElement('input');
  __el_15.id = 'sandi';
  __el_15.setAttribute('tipe', 'password');
  __el_15.placeholder = '••••••';
  __el_15.addEventListener('input', (event) => {
    try {
      __setState(sandi, document.querySelector('#sandi').value);
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_diketik');
    }
  });
  __el_7.appendChild(__el_15);
  const __el_17 = document.createElement('span');
  __el_17.className = 'pesan';
  __el_17.innerText = pesan.value;
  __el_7.appendChild(__el_17);
  const __el_18 = document.createElement('button');
  __el_18.className = 'masuk';
  const __txt_19 = document.createTextNode('Masuk');
  __el_18.appendChild(__txt_19);
  __el_7.appendChild(__el_18);
  __el_7.addEventListener('click', (event) => {
    try {
      if (nama.value === 'admin') {
        localStorage.setItem('auth_token', 'dummy-token-123');
        localStorage.setItem('__peran', 'admin');
        window.location.href = '/dashboard';
      } else {
        __setState(pesan, 'Nama atau sandi salah');
      }
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_diklik');
    }
  });
  __el_3.appendChild(__el_7);
  __el_1.appendChild(__el_3);
  document.body.appendChild(__el_1);
})();
