// Generated by PromptJS Compiler v0.9
// Source: promptjs

// === Runtime Helpers ===
function __pjs_handleError(error, context, hook) {
  console.error("[PromptJS] Error di " + context + "." + hook + ":", error);
  if (window.__pjsClearError) { window.__pjsClearError(); }
}

// === User Code ===
(function() {
  // @source 0:0 TetapDeclaration
  const judul = "Pengaturan";
  // @source 5:1 BuatStatement
  const __el_1 = document.createElement("div");
  __el_1.id = "pengaturan";
  const __el_2 = document.createElement("div");
  __el_2.className = "kartu";
  const __el_4 = document.createElement("h2");
  const __txt_5 = document.createTextNode("Pengaturan");
  __el_4.appendChild(__txt_5);
  __el_2.appendChild(__el_4);
  const __el_6 = document.createElement("label");
  const __txt_7 = document.createTextNode("Tema");
  __el_6.appendChild(__txt_7);
  __el_2.appendChild(__el_6);
  const __el_8 = document.createElement("select");
  __el_8.id = "tema";
  const __el_10 = document.createElement("opsi[value="terang"]");
  const __txt_11 = document.createTextNode("Terang");
  __el_10.appendChild(__txt_11);
  __el_8.appendChild(__el_10);
  const __el_12 = document.createElement("opsi[value="gelap"]");
  const __txt_13 = document.createTextNode("Gelap");
  __el_12.appendChild(__txt_13);
  __el_8.appendChild(__el_12);
  __el_2.appendChild(__el_8);
  const __el_14 = document.createElement("button");
  __el_14.id = "keluar-akun";
  __el_14.className = "merah";
  const __txt_15 = document.createTextNode("Keluar dari Akun");
  __el_14.appendChild(__txt_15);
  __el_2.appendChild(__el_14);
  __el_2.addEventListener("click", (event) => {
    try {
      localStorage.removeItem("auth_token");
      localStorage.removeItem("__peran");
      window.location.href = "/login";
    } catch(__e) {
      __pjs_handleError(__e, "fragment", "on_diklik");
    }
  });
  __el_1.appendChild(__el_2);
  document.body.appendChild(__el_1);
})();