// Generated by PromptJS Compiler v0.9
// Source: promptjs

// === Runtime Helpers ===
var __subscribers = new WeakMap();
var __effectMap = new WeakMap();
var __activeEffect = null;
var __effectId = 0;

function __createReactive(val) {
  var obj = { value: val, __id: ++__effectId };
  var proxy = new Proxy(obj, {
    get: function (target, prop) {
      if (__activeEffect && prop === 'value') {
        var subs = __subscribers.get(proxy) || new Set();
        subs.add(__activeEffect);
        __subscribers.set(proxy, subs);
        if (__activeEffect.__deps) __activeEffect.__deps.add(proxy);
      }
      return target[prop];
    },
    set: function (target, prop, newVal) {
      var oldVal = target[prop];
      target[prop] = newVal;
      if (prop === 'value' && oldVal !== newVal) {
        var subs = __subscribers.get(proxy);
        if (subs) {
          var subsCopy = Array.from(subs);
          for (var i = 0; i < subsCopy.length; i++) subsCopy[i](newVal, oldVal);
        }
      }
      return true;
    },
  });
  return proxy;
}

function __setState(reactive, val) {
  reactive.value = val;
}

function __pjs_handleError(error, context, hook) {
  console.error('[PromptJS] Error di ' + context + '.' + hook + ':', error);
  if (window.__pjsClearError) {
    window.__pjsClearError();
  }
}

// === User Code ===
(function () {
  // @source 0:0 TetapDeclaration
  const judul = 'Profil';
  // @source 5:1 BuatStatement
  const __el_1 = document.createElement('div');
  __el_1.id = 'profil';
  const nama = __createReactive('');
  const peran = __createReactive('');
  __el_1.addEventListener('load', (event) => {
    try {
      __setState(nama, localStorage.getItem('auth_token'));
      __setState(peran, localStorage.getItem('__peran'));
    } catch (__e) {
      __pjs_handleError(__e, 'fragment', 'on_muat');
    }
  });
  const __el_4 = document.createElement('div');
  __el_4.className = 'kartu';
  const __el_6 = document.createElement('h2');
  const __txt_7 = document.createTextNode('Profil Pengguna');
  __el_6.appendChild(__txt_7);
  __el_4.appendChild(__el_6);
  const __el_8 = document.createElement('div');
  __el_8.className = 'profil-info';
  const __el_10 = document.createElement('label');
  const __txt_11 = document.createTextNode('Token');
  __el_10.appendChild(__txt_11);
  __el_8.appendChild(__el_10);
  const __el_12 = document.createElement('span');
  __el_12.innerText = nama.value;
  __el_8.appendChild(__el_12);
  const __el_13 = document.createElement('label');
  const __txt_14 = document.createTextNode('Peran');
  __el_13.appendChild(__txt_14);
  __el_8.appendChild(__el_13);
  const __el_15 = document.createElement('span');
  __el_15.innerText = peran.value;
  __el_8.appendChild(__el_15);
  __el_4.appendChild(__el_8);
  __el_1.appendChild(__el_4);
  document.body.appendChild(__el_1);
})();
